// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/home/bar.vue')['default']
    Category: typeof import('./src/components/category/category.vue')['default']
    Child: typeof import('./src/components/home/child.vue')['default']
    Class: typeof import('./src/components/util/headed/class.vue')['default']
    Divider: typeof import('./src/components/util/divider/divider.vue')['default']
    Headed: typeof import('./src/components/util/headed/headed.vue')['default']
    Home: typeof import('./src/components/home/home.vue')['default']
    Logo: typeof import('./src/components/util/headed/logo.vue')['default']
    Mv: typeof import('./src/components/home/mv.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEl: typeof import('naive-ui')['NEl']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NPagination: typeof import('naive-ui')['NPagination']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NThing: typeof import('naive-ui')['NThing']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/search.vue')['default']
    Searcher: typeof import('./src/components/util/headed/searcher.vue')['default']
    SearchItem: typeof import('./src/components/search/searchItem.vue')['default']
    SearchMv: typeof import('./src/components/search/searchMv.vue')['default']
    Video: typeof import('./src/components/video/video.vue')['default']
  }
}
