// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/home/bar.vue')['default']
    Category: typeof import('./src/components/category/category.vue')['default']
    Child: typeof import('./src/components/home/child.vue')['default']
    Class: typeof import('./src/components/util/headed/class.vue')['default']
    Divider: typeof import('./src/components/util/divider/divider.vue')['default']
    Head: typeof import('./src/components/head/head.vue')['default']
    Headd: typeof import('./src/components/headed/headd.vue')['default']
    Headed: typeof import('./src/components/util/headed/headed.vue')['default']
    Header: typeof import('./src/components/header/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home/home.vue')['default']
    Logo: typeof import('./src/components/util/headed/logo.vue')['default']
    Mv: typeof import('./src/components/home/mv.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDivider: typeof import('naive-ui')['NDivider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NPagination: typeof import('naive-ui')['NPagination']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/search.vue')['default']
    Searcher: typeof import('./src/components/util/headed/searcher.vue')['default']
    Video: typeof import('./src/components/video/video.vue')['default']
  }
}
